# Generated by Django 4.2.2 on 2023-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eqapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='City',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='Country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='Phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
