# Generated by Django 4.2.2 on 2023-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eqapp', '0002_register_city_register_country_register_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_id', models.IntegerField()),
                ('Owner_Name', models.CharField(max_length=20)),
                ('Container_Type', models.CharField(max_length=50)),
                ('Container_Size', models.CharField(max_length=10)),
                ('Container_Picture', models.FileField(upload_to='')),
                ('Quantity', models.IntegerField()),
                ('Container_Amount', models.FloatField()),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
