# Generated by Django 4.2.2 on 2023-07-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eqapp', '0003_containerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lessee_id', models.IntegerField()),
                ('Lessee_Name', models.CharField(max_length=20)),
                ('Owner_id', models.IntegerField()),
                ('Owner_Name', models.CharField(max_length=20)),
                ('Lease_Container_Type', models.CharField(max_length=50)),
                ('Lease_Container_Size', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
                ('Lease_Date', models.DateTimeField()),
                ('Leasing_Months', models.IntegerField()),
                ('Lease_Amount', models.FloatField()),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
