# Generated by Django 4.2.2 on 2023-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_id', models.IntegerField()),
                ('Owner_Name', models.CharField(max_length=20)),
                ('Container_Type', models.CharField(max_length=50)),
                ('Container_Size', models.CharField(max_length=10)),
                ('Container_Picture', models.FileField(upload_to='')),
                ('Quantity', models.IntegerField()),
                ('Container_Amount', models.FloatField()),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeasingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lessee_id', models.IntegerField()),
                ('Lessee_Name', models.CharField(max_length=20)),
                ('Owner_id', models.IntegerField()),
                ('Owner_Name', models.CharField(max_length=20)),
                ('Lease_Container_Type', models.CharField(max_length=50)),
                ('Lease_Container_Size', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
                ('Lease_Date', models.DateTimeField()),
                ('Leasing_Months', models.IntegerField()),
                ('Lease_Amount', models.FloatField()),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LesseeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Company', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LessorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
