from django.urls import path
from . import views

urlpatterns = [
    path('',views.loginpage),
    path('home/',views.loginpage),
    path('register/',views.registerpage),
    path('admin1/',views.adminpage),
    path('adminhome/',views.adminhome),
    path('lessorhome/',views.lessorhome),
    path('lessoredit/',views.lessoredit),
    path('edit/<int:id>',views.edit),
    path('addcon/',views.lessoraddcontainer),
    path('upcon/', views.lessorupdatecontainer),
    path('uedit/<int:id>/', views.lessorupdatecontainer2),
    path('viewlcon/',views.viewlcon),
    path('lessorpending/', views.adminlessorpending),
    path('admin_lessorpending_approve/<int:id>/', views.admin_lessorpending_approve),
path('lesseereg/', views.lessee_register),
    path('lesseelogreg/', views.lessee_log_reg),
    path('lessee_home/', views.lessee_home),
path('lesseepending/', views.admin_lesseepending),
    path('admin_lesseepending_approve/<int:id>/', views.admin_lesseepending_approve),
    path('lessorapprove/', views.admin_lessorapprove),
    path('lesseeapprove/', views.admin_lesseeapprove),
path('lessee_editprofile/', views.lessee_editprofile),
    path('lessee_editprofile_edit/<int:id>/', views.lessee_editprofile_edit),
    path('lessee_view_container_list/', views.lessee_view_container_list),
    path('lessee_lease_container/<int:id>/', views.lessee_lease_container),
    path('lessee_view_leasing_list/', views.lessee_view_leasing_list),
]